# Generated by Django 3.1.1 on 2021-01-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=40, null=True)),
                ('item_name', models.CharField(blank=True, max_length=40, null=True)),
                ('receive_by', models.CharField(blank=True, max_length=40, null=True)),
                ('price', models.IntegerField(blank=True, default='0', null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_to', models.CharField(blank=True, max_length=40, null=True)),
                ('issue_by', models.CharField(blank=True, max_length=40, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('export_to_csv', models.BooleanField(default=False)),
            ],
        ),
    ]
