# Generated by Django 3.1.1 on 2021-02-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0002_auto_20210213_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='from_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
