# Generated by Django 3.1.1 on 2021-02-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0003_auto_20210220_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='to_date',
        ),
    ]
